// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: server/chorepb/chore.proto

package chorepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerType int32

const (
	ServerType_LEADER   ServerType = 0
	ServerType_FOLLOWER ServerType = 1
)

// Enum value maps for ServerType.
var (
	ServerType_name = map[int32]string{
		0: "LEADER",
		1: "FOLLOWER",
	}
	ServerType_value = map[string]int32{
		"LEADER":   0,
		"FOLLOWER": 1,
	}
)

func (x ServerType) Enum() *ServerType {
	p := new(ServerType)
	*p = x
	return p
}

func (x ServerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerType) Descriptor() protoreflect.EnumDescriptor {
	return file_server_chorepb_chore_proto_enumTypes[0].Descriptor()
}

func (ServerType) Type() protoreflect.EnumType {
	return &file_server_chorepb_chore_proto_enumTypes[0]
}

func (x ServerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerType.Descriptor instead.
func (ServerType) EnumDescriptor() ([]byte, []int) {
	return file_server_chorepb_chore_proto_rawDescGZIP(), []int{0}
}

type GetHeartBeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerName string     `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Status     int32      `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	ServerType ServerType `protobuf:"varint,3,opt,name=server_type,json=serverType,proto3,enum=chorepb.ServerType" json:"server_type,omitempty"`
}

func (x *GetHeartBeatRequest) Reset() {
	*x = GetHeartBeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_chorepb_chore_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHeartBeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeartBeatRequest) ProtoMessage() {}

func (x *GetHeartBeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_chorepb_chore_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeartBeatRequest.ProtoReflect.Descriptor instead.
func (*GetHeartBeatRequest) Descriptor() ([]byte, []int) {
	return file_server_chorepb_chore_proto_rawDescGZIP(), []int{0}
}

func (x *GetHeartBeatRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *GetHeartBeatRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetHeartBeatRequest) GetServerType() ServerType {
	if x != nil {
		return x.ServerType
	}
	return ServerType_LEADER
}

type GetHeartBeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GetHeartBeatResponse) Reset() {
	*x = GetHeartBeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_chorepb_chore_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHeartBeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeartBeatResponse) ProtoMessage() {}

func (x *GetHeartBeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_chorepb_chore_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeartBeatResponse.ProtoReflect.Descriptor instead.
func (*GetHeartBeatResponse) Descriptor() ([]byte, []int) {
	return file_server_chorepb_chore_proto_rawDescGZIP(), []int{1}
}

func (x *GetHeartBeatResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_server_chorepb_chore_proto protoreflect.FileDescriptor

var file_server_chorepb_chore_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x63, 0x68, 0x6f, 0x72, 0x65, 0x70, 0x62,
	0x2f, 0x63, 0x68, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x68,
	0x6f, 0x72, 0x65, 0x70, 0x62, 0x22, 0x84, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x34, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x63, 0x68,
	0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x22, 0x2e, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x26, 0x0a, 0x0a,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x45,
	0x41, 0x44, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x4f, 0x4c, 0x4c, 0x4f, 0x57,
	0x45, 0x52, 0x10, 0x01, 0x42, 0x1a, 0x5a, 0x18, 0x72, 0x65, 0x62, 0x69, 0x74, 0x63, 0x61, 0x73,
	0x6b, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x63, 0x68, 0x6f, 0x72, 0x65, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_chorepb_chore_proto_rawDescOnce sync.Once
	file_server_chorepb_chore_proto_rawDescData = file_server_chorepb_chore_proto_rawDesc
)

func file_server_chorepb_chore_proto_rawDescGZIP() []byte {
	file_server_chorepb_chore_proto_rawDescOnce.Do(func() {
		file_server_chorepb_chore_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_chorepb_chore_proto_rawDescData)
	})
	return file_server_chorepb_chore_proto_rawDescData
}

var file_server_chorepb_chore_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_server_chorepb_chore_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_server_chorepb_chore_proto_goTypes = []interface{}{
	(ServerType)(0),              // 0: chorepb.ServerType
	(*GetHeartBeatRequest)(nil),  // 1: chorepb.GetHeartBeatRequest
	(*GetHeartBeatResponse)(nil), // 2: chorepb.GetHeartBeatResponse
}
var file_server_chorepb_chore_proto_depIdxs = []int32{
	0, // 0: chorepb.GetHeartBeatRequest.server_type:type_name -> chorepb.ServerType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_server_chorepb_chore_proto_init() }
func file_server_chorepb_chore_proto_init() {
	if File_server_chorepb_chore_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_chorepb_chore_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHeartBeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_chorepb_chore_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHeartBeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_chorepb_chore_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_chorepb_chore_proto_goTypes,
		DependencyIndexes: file_server_chorepb_chore_proto_depIdxs,
		EnumInfos:         file_server_chorepb_chore_proto_enumTypes,
		MessageInfos:      file_server_chorepb_chore_proto_msgTypes,
	}.Build()
	File_server_chorepb_chore_proto = out.File
	file_server_chorepb_chore_proto_rawDesc = nil
	file_server_chorepb_chore_proto_goTypes = nil
	file_server_chorepb_chore_proto_depIdxs = nil
}
